using Nethereum.Signer;
using TaikoSharp.Services;
TaikoL1Client taikoL1Client = new TaikoL1Client();
TaikoL2Client taikoL2Client = new TaikoL2Client();
var taikoL1ChainID = await taikoL1Client.GetChainIdAsync();
var taikoL2ChainID = await taikoL2Client.GetChainIdAsync();
Console.WriteLine($"Taiko L2 Chain ID: {taikoL1ChainID}");
Console.WriteLine($"Taiko L2 Chain ID: {taikoL2ChainID}");
Console.WriteLine("Enter to exit:");
Console.ReadLine();