using Nethereum.Signer;
using TaikoSharp.Services;
TaikoL1Client taikoL1Client = new TaikoL1Client("https://mainnet.infura.io/v3/53173af3389645d18c3bcac2ee9a751c");
TaikoL2Client taikoL2Client = new TaikoL2Client("https://mainnet.infura.io/v3/53173af3389645d18c3bcac2ee9a751c");
var taikoL1ChainID = await taikoL1Client.GetChainIdAsync();
var taikoL1Syncing = await taikoL1Client.GetSyncingStatusAsync();
var taikoL1BlockNumber = await taikoL1Client.GetLatestBlockNumberAsync();
var taikoL1BlockWithDetails = await taikoL1Client.GetBlockByNumberWithTransactionDetailsAsync(taikoL1BlockNumber.ToString());
var taikoL1BlockWithoutDetails = await taikoL1Client.GetBlockByNumberWithoutTransactionDetailsAsync(taikoL1BlockNumber.ToString());
Console.WriteLine($"Chain ID: {taikoL1ChainID}");
Console.WriteLine($"Syncing: {taikoL1Syncing}");
Console.WriteLine($"Latest Block Number: {taikoL1BlockNumber}");
Console.WriteLine($"Block With Details 1st Transaction Hash:{taikoL1BlockWithDetails.transactions[0].hash}");
Console.WriteLine($"Block Without Details 1st Transaction Hash:{taikoL1BlockWithoutDetails.transactions[0]}");
Console.WriteLine("Enter to exit:");
Console.ReadLine();